apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weatherforecast
  description: weatherforecast API
  tags:
    - weather
    - forecast
    - rest
  links:
    - url: https://github.com/mgbrodi/weatherforecast
      title: GitHub Repo
      icon: github
spec:
  type: openapi
  lifecycle: experimental
  owner: default-team
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/main/APIs/archive.org/wayback/1.0.0/openapi.yaml