apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weatherforecast
  description: weatherforecast API
  tags:
    - weather
    - forecast
    - rest
  links:
    - url: https://github.com/mgbrodi/weatherforecast
      title: GitHub Repo
      icon: github
spec:
  type: openapi
  lifecycle: experimental
  owner: default-team
  definition:
    $text: https://weatherforecast.cody.tap-view.tanzu-azure-lab.winterfell.fun/swagger/v1/swagger.yaml