apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weatherforecast
  description: weatherforecast API
  tags:
    - weather
    - forecast
    - rest
  links:
    - url: https://github.com/mgbrodi/weatherforecast
      title: GitHub Repo
      icon: github
spec:
  type: openapi
  lifecycle: experimental
  owner: dev-team-1
  definition: |
    openapi: 3.0.1
    info:
      title: weatherforecast
      version: '1.0'
    paths:
      /WeatherForecast:
        get:
          tags:
            - WeatherForecast
          responses:
            '200':
              description: Success
              content:
                text/plain:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/WeatherForecast'
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/WeatherForecast'
                text/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/WeatherForecast'
    components:
      schemas:
        WeatherForecast:
          type: object
          properties:
            date:
              type: string
              format: date-time
            temperatureC:
              type: integer
              format: int32
            temperatureF:
              type: integer
              format: int32
              readOnly: true
            summary:
              type: string
              nullable: true
          additionalProperties: false
